### PR TITLE
Update promises.json

### PR DESCRIPTION
**Pull request by prof3ssorSt3v3**
Updated the year prefix to 17: for both nodes inside "basics".

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Sorry about the confusion. But the basics nodes have steps `1.` `2.` and so on. 

And articles, talks and videos that are note in basics node may have a year prefix attached. 

I do think that it is a bit unclear on our side though and we will need to make it more clear. Perhaps you have an idea how we can do it. 🙂 

Basics should have steps because we want learning to be linear. You learn this first, then learn this, covering any knowledge dependencies on your way. And the year prefixes just add context to articles and blogs because it's good to know if an article/video is not outdated.

**Comment by prof3ssorSt3v3** [comment]
Thanks Nikita for the explanation.


So, the article inside basics currently labelled 1. and the video tutorial playlist that I added (originally with 2.) are both covering the basics. They just are done in different formats and with a slightly different approach.


So, how do you decide on the numbering then? Does it matter?


How long does it take for another item to appear?  Eg: The JS Promises video playlist that I added yesterday.


Thanks,

Steve

________________________________

**Comment by nikitavoloboev** [comment]
The numbering is decided by the community. The idea is that step `2.` needs some knowledge from what was covered in `1.` steps. In your case, it falls under `1.` too as it explains promises too same as article linked there but in a different (video) approach and the explanation was really good so it was added.

The [Javascript Promises](https://learn-anything.xyz/programming/programming-languages/javascript/promises) map is updated. 🙂

**Comment by prof3ssorSt3v3** [comment]
Thanks!

________________________________

**Pull request closed without merging**
